# **Python for Neuro:** Week 5

Today, we'll review functions and learn how to use numpy!

## Exercise

Write a function (called `collatz`) that takes in a starting value and prints out each value of the Collatz sequence. As a reminder, the rule was:
- if the previous value $n$ was even, the next value is $n/2$.
- if the previous value was odd, the next value is $3n+1$.
Let the function end when the value taken is $1$.

In [9]:
def collatz(number):
    while(number != 1):
        if number%2==0:
            number=number/ 2
        else:
           number=3*number+1
        print(number)

   

In [10]:
collatz(10)

5.0
16.0
8.0
4.0
2.0
1.0


## return

The return sequence leaves the function and returns any variable coming afterwards.

In [11]:
def fib_return (n):
  """
  Print fibonnacci series up to n.
  Args:
      n (int): Maximum value of the fibonacci series to return.
  Returns:
      list: List of fibonacci sequence values
  """

  fib_list = []
  a,b = 0, 1
  while a <n:
    fib_list.append(a)
    next= a+b
    a = b
    b = next
  return fib_list

In [12]:
fib_return(1000)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

In [13]:
my_fib_list = fib_return(1000)

In [14]:
my_fib_list

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]

Idea with return:
assign output to a variable so you can access it later down the road
can run things without a return

## Default arguments

In [15]:
# We cannot run fib_return without specifying n:
fib_return()

TypeError: fib_return() missing 1 required positional argument: 'n'

In [16]:
# Default arguments can be specified but don't have to be:
def fib_return (n=1):
  """
  Print fibonnacci series up to n.
  Args:
      n (int): Maximum value of the fibonacci series to return. Default value is 1.
  Returns:
      list: List of fibonacci sequence values
  """

  fib_list = []
  a,b = 0, 1
  while a <n:
    fib_list.append(a)
    next= a+b
    a = b
    b = next
  return fib_list

In [17]:
fib_return()

[0]

In [18]:
fib_return(10)

[0, 1, 1, 2, 3, 5, 8]

## Warning about default arguments

Your default arguments should never be mutable. Otherwise repeated function calls can interact with each other.

In [19]:
# mutable arguments

def f(a, L=[]):
    L.append(a)
    return L

print(f(1)) # predict what will happen?
print(f(2))
print(f(3))

[1]
[1, 2]
[1, 2, 3]


In [ ]:
# Which data types are mutable -> dictionaries and lists

In [ ]:
# Solution
def f(a, L=None):
    if L is None: # None now provides a marker that we would like to use the default argument.
        L = []
    L.append(a)
    return L

print(f(1))
print(f(2))
print(f(3))

## Exercise

Modify your ```collatz``` function so that it returns a list containing the sequence instead of printing it. Set the default argument to 100.

In [24]:
def collatz(number=100):
    collatz_list = []
    while(number != 1):
        if number%2==0:
            number=number/ 2
        else:
           number=3*number+1
        collatz_list.append(number)
    return collatz_list


In [26]:
myseq =collatz()

In [27]:
myseq

[50.0,
 25.0,
 76.0,
 38.0,
 19.0,
 58.0,
 29.0,
 88.0,
 44.0,
 22.0,
 11.0,
 34.0,
 17.0,
 52.0,
 26.0,
 13.0,
 40.0,
 20.0,
 10.0,
 5.0,
 16.0,
 8.0,
 4.0,
 2.0,
 1.0]

Next step:
create an empty list so you can add stuff to it (append) later on in the code

the indents tell you where things are in the code and what they relate to

## Numpy!

Often times, we want to work with collectons of data. The simplest rendition of this is a list:

In [28]:
lst_1 = [25, 20, 40, 5]

But these lists are missing a lot of functionality that we find useful for handling numerical data. (You may be used to these from Matlab or R.) For example, suppose you want to multiply each number by 2. We may want the following command to work:

In [29]:
2*lst_1

[25, 20, 40, 5, 25, 20, 40, 5]

Yet its output is not what we are looking for. This is because lists are not *vectorized*: they do not assume that operations should be applied elementwise. Instead we would have to use a command like the one below:

In [30]:
lst_2 = [lst_1[i]*2 for i in range(4)]
lst_2

[50, 40, 80, 10]

To address this and other issue that arise in handling numerical data in Python, we can use `numpy`, which stands for numerical data in Python.

So far, we have exclusively used Python's base functionality. `numpy` is the first example of a package that has been contributed by external users and has to be installed manually. It is, however, integral to Python for basically anyone working with numerical data.

In [31]:
import numpy as np

## One-dimensional arrays: Vectors
The central object of interest for numpy is an *array*, which refers to rectangular data (more on this later). The simplest case of an array is a one-dimensional one, a vector. You can create a vector from a list:

In [32]:
lst_1 = [25, 20, 40, 5]
vec_1 = np.array(lst_1)

In [33]:
vec_1

array([25, 20, 40,  5])

In [34]:
type(vec_1)

numpy.ndarray

We can also turn a vector back into a list:

In [35]:
list(vec_1)

[np.int64(25), np.int64(20), np.int64(40), np.int64(5)]

what is going on above this wtf

Using the numpy array, we can now perform mathematical operations in the way we would like (and perhaps expect from e.g. Matlab).

In [36]:
vec_2 = 2*vec_1
vec_2

array([50, 40, 80, 10])

In [37]:
vec_1+vec_2

array([ 75,  60, 120,  15])

In contrast, what happens if we add two lists?

In [38]:
lst_1 + lst_2

[25, 20, 40, 5, 50, 40, 80, 10]

### Differences between lists and vectors
Both lists and vectors can be indexed and we can easily transform an array into a list and vice versa. What are some of their differences?
#### Elementwise operations
We have already covered that arrays have elementwise operations whereas lists do not.
#### Each element must have the same type
Lists can consist of elements with different types:

In [39]:
lst_3 = ['a', 5]
lst_3

['a', 5]

An array, on the other hand, will always have the same data type for each of its elements. If a list with unequal types is converted to an array all its elements are converted to the same data type.

In [40]:
vec_3 = np.array(lst_3)
vec_3

array(['a', '5'], dtype='<U21')

<U21 is the data type corresponding to strings. You usually don't want to rely on this automatic casting functionality and should try to avoid it.

In [41]:
type(vec_3)

numpy.ndarray

How can you print out the type of this vector? Note that `type(vec_3)` gives you the type of the entire object which is a numpy array. Rather you want the type of the individual elements. Try using the autocomplete function to find out.

*Hint* look at what the type information was called above.

In [43]:
vec_3.dtype

dtype('<U21')

We do we not need parentheses after `dtype`? This is because `dtype` is not function, but rather a new type of Python object called an *attribute*. These are like variables, but are limited in scope to specific objects. We will get to know them in more depth in a later lesson.

### Question 1

- Create a numpy array with the elements 3, 7, 10 and divide each element by two
- Create a new array `vec_4` that is the elementwise multiplication of `vec_1` and `vec_2`.
- Create an array `vec_5` that has a `True` value wherever `vec_1` is smaller than or equal to `20` and a `False` value otherwise. *Hint:* This should be possible in a one liner.

In [76]:
vec_1 = np.array([3,7,10])
vec_1/2

array([1.5, 3.5, 5. ])

In [77]:
vec_4 = vec_1 * vec_2
vec_4

array([ 4.5, 24.5, 45. ])

In [ ]:
vec_5 = vec_1 <= 20
vec_5

## Two-dimensional arrays: Matrices
Rectangular data in two dimensions is often called a matrix: it consists of observations organized by rows and columns. Basic Python would allow us to store such data using a list of lists:

In [63]:
lst_1 = [
    [1, 2],
    [3, 4],
    [5, 6]
]
lst_1

[[1, 2], [3, 4], [5, 6]]

Yet the already tedious process of computing elementwise operations quickly becomes infeasible in this context. If wanted to multiply each element by two we would have to iterate over the outer list and then the inner set of lists.

In [64]:
lst_2 = [
    [2*it2 for it2 in it] for it in lst_1
]
lst_2

[[2, 4], [6, 8], [10, 12]]

Again we can turn the list of lists into a matrix simply by applying `np.array`:

In [65]:
mat_1 = np.array(lst_1)
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

Now we can apply vectorized operations as previously:

In [66]:
mat_2 = 2*mat_1
mat_2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

How can you find out the number of rows and columns of the matrix? Try googling or exploring the methods using the autocomplete function.

In [67]:
mat_1.shape

(3, 2)

this is telling you there are 3 rows and 2 columns
rows by columns

Importantly, numpy, by default, uses elementwise computations. So `*` results in elementwise multiplication, not matrix multiplication.

In [68]:
mat_1*mat_2

array([[ 2,  8],
       [18, 32],
       [50, 72]])

You can run matrix multiplication by using the `@` operator.

In [69]:
mat_3 = np.array([[1,2],[3,4]])
mat_1@mat_3

array([[ 7, 10],
       [15, 22],
       [23, 34]])

use the @ sign for matrix multiplication

### Saving arrays
We can save arrays using `np.save`.

In [70]:
np.save('mat_1.npy', mat_1)

In [71]:
mat_1_copy = np.load('mat_1.npy')

this is helpful if you want to save analysis of data

In [72]:
mat_1_copy

array([[1, 2],
       [3, 4],
       [5, 6]])

## Higher-dimensional arrays

We now load some simulated data, which is stored in the file `ex_array.npy`. Try assigning the data in that file to the variable `arr`.

In [73]:
arr = np.load('ex_array.npy')

Suppose you know that what is stored in this data are spike rates of fifty different neurons for two different conditions and ten repeated measurements. Spike rates are recorded every second for 2000 seconds. How can you figure out how this data is represented in the array?

In [81]:
arr.shape

(2, 10, 50, 2000)

In [82]:
arr.ndim

4

.ndim tells you how many dimensions there are

Whereas a vector has one dimension and a matrix has two dimensions, `arr` has four dimensions: the first one specifies the condition, the second one the trial, the third one the neuron, and the fourth one the timepoint. We can also create higher-dimensional arrays directly:

In [83]:
arr_2 = np.array([
    [[2,4,6],
     [1,3,5]],
    [[0.5,1,2],
     [0.75, 1, 1.25]]
])

What is `arr_2.ndim` and `arr_2.shape`?

In [85]:
arr_2.ndim
# 3

3

In [ ]:
arr_2.shape
#2,2  3
# there are two lists with 2 lists in them and each list has 3 elements

(2, 2, 3)

### Data must be rectangular
Importantly numpy only allows for rectangular data. What happens if you create an array from a list of lists with unequal length?

In [86]:
mat = np.array([[1,2],[3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
mat
#no clue what they wanted me to do here because I wasn't in class oops

### Broadcasting

In general you cannot add two matrices with different shapes:

In [91]:
mat_1.shape

(3, 2)

In [92]:
mat_3 = np.array([
    [1,2,3],
    [1,2,3]
])

In [93]:
mat_3.shape

(2, 3)

In [94]:
mat_1+mat_3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

Elementwise operations can work between two arrays with unequal shapes:
- If they match everywhere except where one of them has a dimension of length 1
- If they have an unequal number of dimensions, the array with fewer dimensions is appended dimensions of length 1 in the beginning.

In [95]:
np.array([
    [1,2]
]) + np.array([
    [1,2],
    [3,4],
    [5,6]
])

array([[2, 4],
       [4, 6],
       [6, 8]])

The same thing is true for matrices with one column or other elementwise operations.

In [96]:
divisor = np.array([[2], [1], [1]])

In [97]:
divisor.shape

(3, 1)

In [98]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
mat_1 / divisor

array([[0.5, 1. ],
       [3. , 4. ],
       [5. , 6. ]])

In [102]:
vec_4 = np.array([1, 2])
vec_4

array([1, 2])

In [101]:
vec_4.shape

(2,)

In [103]:
vec_4+mat_1

array([[2, 4],
       [4, 6],
       [6, 8]])

### Creating some arrays

In [ ]:
np.linspace(0, 1, 21)
# np.linspace() is a function that returns an array of evenly spaced numbers over a specified interval.

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [ ]:
np.arange(10)
# np.arange() creates a NumPy array with evenly spaced values within a given range (in this case 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2)
# This tells NumPy to generate an array starting at 1, stopping before 10, and increasing by 2 each time.
''' np.arrange(a,b,c)
parameters:
element a = tells array where to start
element b = tells array what number to stop before
element c = interval
'''

array([1, 3, 5, 7, 9])

In [ ]:
np.ones((4, 2, 3))
# This creates a NumPy array filled with 1.0, with the shape (4, 2, 3) — that is, a 3-dimensional array.
# This tells NumPy to generate 4 sets, with 2 rows and 3 values

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

### Question 2

Below we're creating arrays with different shapes. Try predicting for each if elementwise addition would work, what shape the resulting array would have, then try it out and see if you were correct.

In [110]:
arr_1 = np.ones((3,2))
arr_2 = np.ones((2,3))
'''
array 1 = array filled with ones, shape 3 x 2 - 2d array
array 2 = array filled with ones, shape 2 x 3 - 2d array

Can't do it because they are different shapes
'''
arr_3 = arr_1 + arr_2


ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,5))

'''
array 1 = 3d array, 4 x1 x5
array 2 = 3d array, 4 x 6 x 5

I think you can add them
shouldn't it be all ones in the code
'''
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [ ]:
arr_1 = np.ones((4,1,5))
arr_2 = np.ones((4,6,1))
''' I think you can add them because they are the same shape
but lowkey it seems like something is wrong - shouldn't it be all ones in the code'''
arr_1 + arr_2

array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((3,5))
arr_1 + arr_2

''' you can add because same shape...'''


array([[[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]])

In [ ]:
arr_1 = np.ones((4,3,5))
arr_2 = np.ones((4,3))
arr_1 + arr_2
''' can't add becasue not same shape 
arr_2 is a vertical rectangle?'''

ValueError: operands could not be broadcast together with shapes (4,3,5) (4,3) 

I don't really get when you can add arrays and when you can't

## Summary operations

Summary operations allow you to collapse an array according to a certain summary statistic. For instance, we may want to compute the overall mean firing rate in our experimental data:

In [121]:
arr.mean()

np.float64(0.8717270073789575)

You can also specify the axis along we want to average. For instance, maybe we want to average firing rates across individual trials:

In [122]:
arr.shape

(2, 10, 50, 2000)

In [123]:
arr_across_trials = arr.mean(axis=1)

In [124]:
arr_across_trials.shape

(2, 50, 2000)

axis 1 is for the individual trials

If you don't use keepdims it will remove the dimension your averaging over - why there are only 3 listed

The `keepdims` argument means that you don't remove the dimensions you're averaging over, but rather set their length to 1:

In [125]:
arr_across_trials = arr.mean(axis=1, keepdims=True)

In [126]:
arr_across_trials.shape

(2, 1, 50, 2000)

Where do you actually see the average of that dimension tho?

You can average across multiple axes as well. For instance, maybe you want to average across both trials and time:

In [127]:
arr_across_trials_and_time = arr.mean(axis=(1,3))

In [128]:
arr_across_trials_and_time.shape

(2, 50)

I don't really get how to interpret this output

### Question 3

- What is the average firing rate across all neurons, times, and trials for each condition?
- (Advanced.) Subtract the average firing rate per time across all neurons, trials, and conditions from the original array.

In [130]:
arr_across_neurons_times_trials = arr.mean(axis=(1, 2, 3))
arr_across_neurons_times_trials.shape

(2,)

In [ ]:
#Advanced
arr_across_neuron_trial_condition =

(2,)

Figure out how to do the one above

## Indexing

Indexing in vectors works just as in lists:

In [132]:
vec_1

array([ 3,  7, 10])

In [133]:
vec_1[0]

np.int64(3)

why does it show the np.int64???

For matrices and higher-dimensional arrays, a single index selects a single row:

In [134]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [135]:
mat_1[0]

array([1, 2])

In [ ]:
mat_1[0][1]
# to get element in the second column in the first row

np.int64(2)

Instead of using two brackets, you can also separate the row and column index by a comma:

In [137]:
# The following two lines of code are equivalent
print(mat_1[0][0])
print(mat_1[0,0])

1
1


### Slicing

Slicing is a useful way of extracting more than one element. In particular, `j:k` extracts the elements j,...,k-1:

In [138]:
vec = np.arange(10)
print(vec)

[0 1 2 3 4 5 6 7 8 9]


In [139]:
vec[3:7]

array([3, 4, 5, 6])

We can leave either end of the range away and it will default to the beginning and the end of the list, respectively.

In [140]:
vec[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [141]:
vec[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
vec[:] # What do you think this will do?
# it leaves it as is?

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You can therefore also use the colon to select all rows of a matrix and specific columns.

In [143]:
mat_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
mat_1[:,0]

array([1, 3, 5])

You can add another colon to specify a step size, similarly to how you would use these three arguments in `range`.

In [ ]:
vec[3:7:2]
# this would be slicing 2 - 7 going up by 2 and excluding 7

array([3, 5])

Review how to use three arguments in range

We could still leave away the beginning or the end of the slice:

In [ ]:
vec[::2]
# this slices the whole thing in increments of 2

array([0, 2, 4, 6, 8])

### Question 4
Predict the output of the following commands:

In [ ]:
vec[:4]
# [0, 1, 2, 3]

array([0, 1, 2, 3])

In [149]:
vec[5:9:2]
#[5, 7]

array([5, 7])

In [150]:
vec[:7:2]
#[0, 2, 4, 6]

array([0, 2, 4, 6])

In [ ]:
vec[2::2]
#[2, 4, 6, 8]

array([2, 4, 6, 8])

### Boolean indexing

Do you remember how to create an array that is true if and only if `vec` is smaller than 5?

In [153]:
vec = np.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
selector = vec <= 5
selector

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

You can use these boolean arrays to subset the corresponding true values.

In [155]:
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
vec[selector]

array([0, 1, 2, 3, 4, 5])

In [157]:
vec[vec<=5]

array([0, 1, 2, 3, 4, 5])

You can do the same with matrices:

In [158]:
mat_1 = np.array([[1, 2],
       [3, 4],
       [5, 6]])

In [159]:
mat_1 >= 3

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [160]:
mat_1[mat_1 >= 3]

array([3, 4, 5, 6])

### Questions 5
- Consider the example matrix from above and subset all entries with values between 2 and 4. You can try to do this in one line or do it through multipel lines!

In [ ]:
mat_1[mat_1>= 2 & mat_1<=4]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Check the answer above