# PfN Homework: Week 5

We're going to begin by reviewing some of the ways we can create arrays using numpy's inbuilt functions:

In [1]:
import numpy as np

Let's begin with ```linspace```, which allows us to evenly tile an array with elements from start to finish. We specify the number of steps the function should take. For example, try to predict what the following code will output:

In [ ]:
arr = np.linspace(0, 10, 5)
# range is 0-10 - broken up into 5 numbers
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

What if you want to specify the step *size* instead? Then we can use a complementary function,  ```arange```. Try to guess what ```arr``` will be once again, and then run the code to check whether you were correct.

In [3]:
arr = np.arange(0, 10, 2.5)
arr
# [0, 2.5, 5, 7.5, 10]

array([0. , 2.5, 5. , 7.5])

It's often useful to also create arrays that consist of the same element. For instance, we can use ```ones``` to create a numpy array of - wait for it - ones. Note here that we're creating a multidimensional array.

why would it be helpful to make a multidimensional array of the same element

In [4]:
arr = np.ones((3, 4, 2))
arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

We can also do more fancy things, like create an identity matrix using ```eye```:


In [5]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Let's practice creating arrays below:

## Question 1:
A) Create a numpy array using ```linspace``` that counts up from 3 to 8 in steps of 0.5.

B) Create the same array, but use ```arange```

C) Using the wonders of the world wide web, please figure out how to create an array of all zeros. Make the array 3x4x5.

In [ ]:
#1A
arr_1 = np.linspace(3,8,11)
arr_1
# i figured this out by counting the numbers but is there a better way to do this...

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ])

In [ ]:
#1B
arr_2= np.arange(3,8,0.5)
arr_2
# doesn't include the last number

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

In [14]:
#1C
arr_3 = np.zeros((3,4,5))
arr_3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# Putting arrays together

What if we want to put arrays together? With lists this is easy: you just add them together. But, as we discussed during class, the whole point of numpy arrays is that when we add them we ... add them. Luckily, as usual, numpy has a function for that.

Let's begin with the simplest example, putting two arrays together:

In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Note that the arrays are provided here as a tuple ... this will be important later
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5, 6])

What if we want to put three arrays together? You can just provide more arrays to the tuple that is given to ```concatenate```.

In [16]:
d = np.concatenate((a, b, c))
d

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

What if we want to put arrays together, over and over again? We can use ```np.tile```

In [ ]:
np.tile(a, 3)
# this adds array a 3x in the new array!

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

You can also use ```tile``` to stack arrays on top of each other. Here, we're telling the function to repeat array ```a``` three times, in one column.

In [18]:
np.tile(a, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

Can you predict what the following code would output?

In [19]:
np.tile(a, (3,2))
# repeats array a 3x in 2 columns

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

There are a ton of other functions that you can use to put arrays together, which you can use flexibly to solve the next few problems. Use the numpy documentation and a bit of googling to find the appropriate functions. As you'll see, there will be multiple ways to solve the same problem!

# Question 2

A) Write a function that takes in a 1D array for input and returns the same array, mirrored, stacked N times, where N is also an input to the function. For instance, given the array ```[1,2,3] ```as an input, and ```N=2```, the function would return ```[[1,2,3,3,2,1], [1,2,3,3,2,1]]```

B) Write another function that takes in a 1D array for input and returns another array, with each element repeated N times. For example, given ```[1,2,3]``` and ```N=3``` the function would return ```[1,1,1,2,2,2,3,3,3]```


In [49]:
#2A
a = np.array([1,2,3])

def mirrorandstack_array(arr: np.array, N:int) -> np.array:
    '''np.ndarray is an N-dimensional array'''

    mirrored_row = np.concatenate([arr, arr[::-1]]) #original plus mirrored row
    stacked_row = np.vstack([mirrored_row] * N)   # stacks the mirrored row N times

    return stacked_row
result = mirrorandstack_array(a, 2)
print(result)

[[1 2 3 3 2 1]
 [1 2 3 3 2 1]]


Why are there no commas
oh is it a 2d array and that's why it's 2 rows
the one didn't print as an array

my two answers below worked but they weren't functions

In [ ]:
#2A
N = 2
arr = np.array([1,2,3])

mirrored_row = np.concatenate([arr, arr[::-1]]) #original plus mirrored row
stacked_row = np.vstack([mirrored_row] * N)   # stacks the mirrored row N times

stacked_row

array([[1, 2, 3, 3, 2, 1],
       [1, 2, 3, 3, 2, 1]])

In [38]:
#2A
N = 2
arr = np.array([1,2,3])

mirrored_row = np.concatenate([arr, arr[::-1]]) #original plus mirrored row
mirror_stack = np.tile([mirrored_row], N)   # stacks the mirrored row N times

mirror_stack

array([[1, 2, 3, 3, 2, 1, 1, 2, 3, 3, 2, 1]])

How do I get it as two separate arrays!!

In [52]:
#2B
'''The numpy.repeat() function in Python's NumPy library is used to repeat elements of an array. 
It takes an input array, a number of repetitions for each element, and an optional axis parameter

Syntax:
numpy.repeat(a, repeats, axis=None)

a: The input array whose elements are to be repeated.
repeats: The number of times each element in a should be repeated.
axis: (optional): The axis along which to repeat the values.
If axis=None (default), the input array a is flattened first, and then its elements are repeated. The output is a 1D array.
If axis=0, elements are repeated along the rows (vertical repetition).
If axis=1, elements are repeated along the columns (horizontal repetition).'''


def repeat_elements(arr: np.array, N:int) -> np.array:
    return np.repeat(arr, N)

a = np.array([1,2,3])
repeat_elements(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

why doesn't it print it as an array if you do it is a result and printing of the result - oh is it because it's only printing the values???